
name: github-actions-demo

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          npm:   npm cache clean --force
          npms:   npm install -g @angular/cli
          build: npm run build
          start: npm start
